# Generated by Django 4.0.2 on 2022-04-23 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('categoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_subcategory', to='food_order.category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('isRawMaterial', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=2000)),
                ('image', models.FileField(blank=True, null=True, upload_to='items/')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_item', to='food_order.category')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.CharField(max_length=30, null=True)),
                ('cost', models.FloatField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethod', models.TextField()),
                ('createdDate', models.CharField(max_length=30, null=True)),
                ('address', models.TextField(null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('cost', models.FloatField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('userType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_client', serialize=False, to='food_order.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('userId', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_deliveryman', serialize=False, to='food_order.user')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_supplier', serialize=False, to='food_order.user')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_salesorderitem', to='food_order.item')),
                ('salesOrderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salseorder_salesorderitem', to='food_order.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rawmaterial', to='food_order.item')),
                ('rawMaterialItemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawmaterialitem_rawmaterial', to='food_order.item')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrdersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_purchaseorderitem', to='food_order.item')),
                ('purchaseOrderId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purcahase_purchaseorderitem', to='food_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('clientId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='client_shoppingCart', serialize=False, to='food_order.client')),
            ],
        ),
        migrations.AddField(
            model_name='salesorder',
            name='clientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_salesorder', to='food_order.client'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('createdDate', models.DateTimeField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_review', to='food_order.item')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_review', to='food_order.client')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('createdDate', models.DateTimeField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_rate', to='food_order.item')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_rate', to='food_order.client')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_purchaseorder', to='food_order.supplier'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_favorite', to='food_order.item')),
                ('clientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_favorite', to='food_order.client')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryManId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryMan_delivery', to='food_order.deliveryman')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_shoppingcartitem', to='food_order.item')),
                ('shoppingCartId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcart_shoppingcartitem', to='food_order.shoppingcart')),
            ],
        ),
    ]
