# Generated by Django 4.0.2 on 2022-04-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='salesOrderId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesOrder_delivery', to='food_order.salesorder'),
        ),
    ]
