# Generated by Django 4.0.2 on 2022-02-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0002_alter_category_id_alter_favorite_id_alter_item_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
