# Generated by Django 4.0.2 on 2022-04-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0003_alter_salesorderitem_salesorderid'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewOrdersItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_neworderitem', to='food_order.item')),
                ('newOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neworder_neworderitem', to='food_order.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.CharField(max_length=30, null=True)),
                ('cost', models.FloatField(blank=True, max_length=20, null=True)),
                ('supplierId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_neworder', to='food_order.supplier')),
            ],
        ),
    ]
