# Generated by Django 4.0.2 on 2022-02-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0003_alter_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(max_length=20),
        ),
    ]
