# Generated by Django 4.0.2 on 2022-04-26 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0005_alter_purchaseorder_supplierid'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseordersitem',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='newordersitem',
            name='newOrderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neworder_neworderitem', to='food_order.neworder'),
        ),
    ]
