# Generated by Django 4.0.2 on 2022-04-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0006_purchaseordersitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('userId', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_adminuser', serialize=False, to='food_order.user')),
            ],
        ),
    ]
