# Generated by Django 4.0.2 on 2022-04-28 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0008_alter_category_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categoryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_item', to='food_order.category'),
        ),
    ]
