# Generated by Django 4.0.2 on 2022-05-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0012_alter_category_categoryid_alter_item_categoryid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
