# Generated by Django 4.0.2 on 2022-05-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0013_remove_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neworder',
            name='supplierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_neworder', to='food_order.supplier'),
        ),
    ]
