# Generated by Django 4.0.2 on 2022-05-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0015_alter_neworder_supplierid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
