# Generated by Django 4.0.2 on 2022-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0017_recipy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipy',
            new_name='Recipe',
        ),
    ]
