# Generated by Django 4.0.2 on 2022-05-01 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0018_rename_recipy_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rawMaterialId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawMaterial_recipy', to='food_order.item'),
        ),
    ]
