# Generated by Django 4.0.2 on 2022-05-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_order', '0019_recipe_rawmaterialid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='createdDate',
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
    ]
